package com.example.kieutrang.e_learning;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageButton;

import com.example.kieutrang.database.MySQLiteOpenHelper;
import com.example.kieutrang.database.Vocabulary;
import com.example.kieutrang.database.Extra;
import com.example.kieutrang.database.Test;
import java.util.ArrayList;

public class E_Learning extends Activity implements View.OnClickListener {
    private ImageButton imgVol, imgExer, imgExtra, imgTest;
    private MySQLiteOpenHelper database ;
    private ArrayList<Vocabulary> arr;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_e__learning);
        overridePendingTransition(R.anim.move, R.anim.movereturn);
        database = new MySQLiteOpenHelper(this);
        arr = database.getAllVol();
        imgVol = (ImageButton) findViewById(R.id.imgVol);
        imgExer = (ImageButton) findViewById(R.id.imgExer);
        imgTest = (ImageButton) findViewById(R.id.imgTest);
        imgExtra = (ImageButton) findViewById(R.id.imgStory);
        imgExer.setOnClickListener(this);
        imgVol.setOnClickListener(this);
        imgTest.setOnClickListener(this);
        imgExtra.setOnClickListener(this);
        if (arr.size() == 0) {
            addDatabase();
            addDbTest();
            addDbExtra();

        }
    }

    @Override
    public void onClick(View v) {
        Intent intent = new Intent();
        switch (v.getId()) {
            case R.id.imgVol:
                intent = new Intent(E_Learning.this, vocabulary.class);
                startActivity(intent);
                finish();
                break;
            case R.id.imgExer:
                intent = new Intent(E_Learning.this, exercise.class);
                startActivity(intent);
                finish();
                break;
            case R.id.imgTest:
                intent = new Intent(E_Learning.this, test_english.class);
                startActivity(intent);
                finish();
                break;
            case R.id.imgStory:
                intent = new Intent(E_Learning.this, extra.class);
                startActivity(intent);
                finish();
                break;
            default:
                break;
        }

    }

    @Override
    public void onBackPressed() {
        // TODO Auto-generated method stub
        super.onBackPressed();
        finish();
    }

    void addDatabase() {
        Vocabulary v1 = new Vocabulary("Lesson 1", "abandon", "/ə'bændən/", "(v) bỏ, từ bỏ", "We had to abandon the car and walk the rest of the way.");
        Vocabulary v2 = new Vocabulary("Lesson 1", "abandoned", "/ə'bændənd/", "(adj) bị bỏ rơi, bị ruồng bỏ", "He was abandoned by his mother as a baby.");
        Vocabulary v3 = new Vocabulary("Lesson 1", "ability", "/ə'biliti/", "(n) khả năng, năng lực", "I have the ability to draw cartoons.");
        Vocabulary v4 = new Vocabulary("Lesson 1", "able", "/'eibl/", "(adj) có năng lực, có tài", "He is able to come with me.");
        Vocabulary v5 = new Vocabulary("Lesson 1", "about", "/ə'baut/", "(adv/prep) khoảng, về", "There's something nice about him");
        Vocabulary v6 = new Vocabulary("Lesson 1", "above", "/ə'bʌv/", "(adv/prep) ở trên, lên trên", "They were all men of fifty and above");
        Vocabulary v7 = new Vocabulary("Lesson 1", "abroad", "/ə'brɔ:d/", "(adv)ra nước ngoài", "These pornographic publications were brought from abroad");
        Vocabulary v8 = new Vocabulary("Lesson 1", "absence", "/'æbsəns/", "(n) sự vắng mặt", "To carry out production in the absence of necessary machines");
        Vocabulary v9 = new Vocabulary("Lesson 1", "absent", "/'æbsənt/", "(adj) vắng mặt, nghỉ", "He answers in an absent way");
        Vocabulary v10 = new Vocabulary("Lesson 1", "absolute", "/'æbsəlu:t/", "(adj) tuyệt đối, hoàn toàn", "She has an absolute evidence");
        Vocabulary v11 = new Vocabulary("Lesson 2", "back", "/bæk/", "(n/adj/adv/v) lưng, về phía sau, trở lại", "animation");
        Vocabulary v12 = new Vocabulary("Lesson 2", "background", "/'bækgraund/", "(n) phía sau, nền", "b");
        Vocabulary v13 = new Vocabulary("Lesson 2", "backward", "/'bækwəd/", "(adj) về phía sau, lùi lại", "a");
        Vocabulary v14 = new Vocabulary("Lesson 2", "bacteria", "/bæk'tiəriəm/", "(n) vi khuẩn", "b");
        Vocabulary v15 = new Vocabulary("Lesson 2", "bad", "/bæd/", "(adj) xấu, tồi", "b");
        Vocabulary v16 = new Vocabulary("Lesson 2", "badly", "/'bædli/", "(adv)  xấu, tồi", "c");
        Vocabulary v17 = new Vocabulary("Lesson 2", "bad-tempered", "/'bæd'tempəd/", "(adj) xấu tính, dễ nổi cáu", "a");
        Vocabulary v18 = new Vocabulary("Lesson 2", "bag", "/bæg/", "(n) bao, túi, cặp xách", "b");
        Vocabulary v19 = new Vocabulary("Lesson 2", "baggage", "/bæɳk/", "(n) hành lý", "c");
        Vocabulary v20 = new Vocabulary("Lesson 2", "bank", "/'æbsəlu:t/", "(n) bờ sông, đê", "a");
        Vocabulary v21 = new Vocabulary("Lesson 3", "cabinet", "/'kæbinit/", "(n) tủ có nhiều ngăn đựng đồ", "animation");
        Vocabulary v22 = new Vocabulary("Lesson 3", "campaign", "/kæmˈpeɪn/ ", "(n) chiến dịch, cuộc vận động", "b");
        Vocabulary v23 = new Vocabulary("Lesson 3", "candidate", "/'kændidit/", "(n) người ứng cử, thí sinh, người dự thi", "a");
        Vocabulary v24 = new Vocabulary("Lesson 3", "capable", "/'keipәb(ә)l/", "(adj) có năng lực, có tài", "b");
        Vocabulary v25 = new Vocabulary("Lesson 3", "capacity", "/kə'pæsiti/", "(n) năng lực, khả năng tiếp thu", "b");
        Vocabulary v26 = new Vocabulary("Lesson 3", "capital", "/ˈkæpɪtl/", "(n/adj) thủ đô, tiền vốn, chủ yếu", "c");
        Vocabulary v27 = new Vocabulary("Lesson 3", "capture", "/'kæptʃə/", "(v/n) bắt giữ, bắt, sự bắt giữ", "a");
        Vocabulary v28 = new Vocabulary("Lesson 3", "combination", "/,kɔmbi'neiʃn/", "(n) sự kết hợp, sự phối hợp", "b");
        Vocabulary v29 = new Vocabulary("Lesson 3", "commission", "/kəˈmɪʃən/", "(n/v) hội đồng, ủy ban, sự ủy nhiệm", "c");
        Vocabulary v30 = new Vocabulary("Lesson 3", "careful", "/'keəful/", "(adj) cẩn thận, cẩn trọng", "a");
        Vocabulary v31 = new Vocabulary("Lesson 4", "daily", "/'deili/", "(adj) hàng ngày", "animation");
        Vocabulary v32 = new Vocabulary("Lesson 4", "damp", "/dæmp/", "(adj) ẩm, ẩm ướt", "b");
        Vocabulary v33 = new Vocabulary("Lesson 4", "dance", "/dɑ:ns/", "(n/v) sự nhảy múa, sự khiêu vũ", "a");
        Vocabulary v34 = new Vocabulary("Lesson 4", "danger", "/'deindʤə/", "(n) sự nguy hiểm, mối hiểm nghèo", "b");
        Vocabulary v35 = new Vocabulary("Lesson 4", "dark", "/dɑ:k/", "(n/adj)  tối, tối tăm; bóng tối", "b");
        Vocabulary v36 = new Vocabulary("Lesson 4", "daughter", "/ˈdɔtər/", "(n/adj) con gái", "c");
        Vocabulary v37 = new Vocabulary("Lesson 4", "deal", "/di:l/", "(v/n) phân phát, phân phối", "a");
        Vocabulary v38 = new Vocabulary("Lesson 4", "debate", "/dɪˈbeɪt/", "(n/v) cuộc tranh luận, cuộc tranh cãi", "b");
        Vocabulary v39 = new Vocabulary("Lesson 4", "decade", "/'dekeid/", "(n) thập kỷ, bộ mười", "c");
        Vocabulary v40 = new Vocabulary("Lesson 4", "decide", "/di'said/", "(v) quyết định, giải quyết", "a");
        Vocabulary v41 = new Vocabulary("Lesson 5", "early", "/´ə:li/", "(adj/adv) sớm", "animation");
        Vocabulary v42 = new Vocabulary("Lesson 5", "easily", "/'i:zili/", "adv) dễ dàng", "b");
        Vocabulary v43 = new Vocabulary("Lesson 5", "east", "/i:st/", "(n/adv/adj) hướng đông, phía đông", "a");
        Vocabulary v44 = new Vocabulary("Lesson 5", "economic", "/¸i:kə´nɔmik/", "(adj) kinh tế", "b");
        Vocabulary v45 = new Vocabulary("Lesson 5", "electronic", "/ɪlɛkˈtrɒnɪk/", "(adj) điện tử", "b");
        Vocabulary v46 = new Vocabulary("Lesson 5", "exhibition", "/ˌɛksəˈbɪʃən/", "( n) cuộc triển lãm, trưng bày", "c");
        Vocabulary v47 = new Vocabulary("Lesson 5", "expand", "/iks'pænd/", "(v) mở rộng, phát triển", "a");
        Vocabulary v48 = new Vocabulary("Lesson 5", "expectation", "/,ekspek'tei∫n/", "(n) sự mong chờ, sự chờ đợi", "b");
        Vocabulary v49 = new Vocabulary("Lesson 5", "emerge", "/i´mə:dʒ/", "(v) nổi lên, hiện ra", "c");
        Vocabulary v50 = new Vocabulary("Lesson 5", "emotion", "/i'moƱʃ(ә)n/", "(n) sự xúc động, sự cảm động", "a");
        Vocabulary v51 = new Vocabulary("Lesson 6", "face", "/feis/", "(n) mặt, thể diện, đương đầu, đối phó", "animation");
        Vocabulary v52 = new Vocabulary("Lesson 6", "facility ", "/fəˈsɪlɪti/ ", "(n) điều kiện dễ dàng, sự dễ dàng, thuận lợi", "b");
        Vocabulary v53 = new Vocabulary("Lesson 6", "fact", "/fækt/", "(n) / việc, sự việc, sự kiện", "a");
        Vocabulary v54 = new Vocabulary("Lesson 6", "factory", "/'fæktəri/", "(n) nhà máy, xí nghiệp, xưởng", "b");
        Vocabulary v55 = new Vocabulary("Lesson 6", "faintly", "/'feintli/", "(adv) nhút nhát, yếu ớt", "b");
        Vocabulary v56 = new Vocabulary("Lesson 6", "fair", "/feə/", "(adj) hợp lý, công bằng, thuận lợi", "c");
        Vocabulary v57 = new Vocabulary("Lesson 6", "famous", "/'feiməs/", "(adj) nổi tiếng", "a");
        Vocabulary v58 = new Vocabulary("Lesson 6", "fashion", "/'fæ∫ən/", "(n) mốt, thời trang", "b");
        Vocabulary v59 = new Vocabulary("Lesson 6", "feature", "/'fi:tʃə/", "(n/v) nét đặt biệt, điểm đặc trưng", "c");
        Vocabulary v60 = new Vocabulary("Lesson 6", "feeling", "/'fi:liɳ/", "(n) sự cảm thấy, cảm giác", "a");
        Vocabulary v61 = new Vocabulary("Lesson 7", "gain", "/geɪn/", "(n/v) lợi, lợi ích", "animation");
        Vocabulary v62 = new Vocabulary("Lesson 7", "gather", "/'gæðə/", "(v) hái, lượm, thu thập", "b");
        Vocabulary v63 = new Vocabulary("Lesson 7", "general", "/'ʤenər(ə)l/", "(adj) chung, chung chung", "a");
        Vocabulary v64 = new Vocabulary("Lesson 7", "generation", "/ˌdʒɛnəˈreɪʃən/", "(n) sự sinh ra, sự phát sinh ra", "b");
        Vocabulary v65 = new Vocabulary("Lesson 7", "generous", "/´dʒenərəs/", "(adv) rộng lượng, hào phóng", "b");
        Vocabulary v66 = new Vocabulary("Lesson 8", "habit", "/´hæbit/", "( n) thói quen, tập quán", "c");
        Vocabulary v67 = new Vocabulary("Lesson 8", "hand", "/'kæptʃə/", "(n/v) tay, bàn tay; trao tay, truyền cho", "a");
        Vocabulary v68 = new Vocabulary("Lesson 8", "happiness", "/'hæpinis/", "(n) sự sung sướng, hạnh phúc", "b");
        Vocabulary v69 = new Vocabulary("Lesson 8", "harmful", "/´ha:mful/", "adj) gây tai hại, có hại", "c");
        Vocabulary v70 = new Vocabulary("Lesson 8", "headache", "/'hedeik/", "(n) chứng nhức đầu", "a");
        Vocabulary v71 = new Vocabulary("Lesson 9", "ideal", "/aɪˈdiəl/", "(adj/n) quan niệm, tư tưởng; lý tưởng", "animation");
        Vocabulary v72 = new Vocabulary("Lesson 9", "imagination", "/i,mædʤi'neiʃn/ ", "(n) trí tưởng tượng, sự tưởng tượng", "b");
        Vocabulary v73 = new Vocabulary("Lesson 9", "impatient", "/im'pei∫зns/", "(adj) thiếu kiên nhẫn, nóng vội", "a");
        Vocabulary v74 = new Vocabulary("Lesson 9", "importance", "/im'pɔ:təns/", "(n) sự quan trọng, tầm quan trọng", "b");
        Vocabulary v75 = new Vocabulary("Lesson 9", "impossible", "/im'pɔsəbl/", "(adj) không thể làm được, không thể xảy ra", "b");
        Vocabulary v76 = new Vocabulary("Lesson 10", "kind", "/kaind/", "( n/adj) loại, giống; tử tế, có lòng tốt", "c");
        Vocabulary v77 = new Vocabulary("Lesson 10", "knowledge ", "/''nɒliʤ/", "(n) sự hiểu biết, tri thức", "a");
        Vocabulary v78 = new Vocabulary("Lesson 10", "knitted ", "/´nitiη/ ", "(n) việc đan; hàng dệt kim", "b");
        Vocabulary v79 = new Vocabulary("Lesson 10", "kitchen ", "/´kitʃin/", "(n) bếp", "c");
        Vocabulary v80 = new Vocabulary("Lesson 10", "knot", "/nɔt/", "(n) cái nơ, điểm nút", "a");
        Vocabulary v81 = new Vocabulary("Lesson 11", "laboratory", "/ˈlæbrəˌtɔri/", "(n) phòng thí nghiệm", "animation");
        Vocabulary v82 = new Vocabulary("Lesson 11", "large", "/la:dʒ/", "(adj) rộng, lớn, to", "b");
        Vocabulary v83 = new Vocabulary("Lesson 11", "latest", "/leitist/", "(n/adj) muộn nhất, chậm nhất, gần đây nhất", "a");
        Vocabulary v84 = new Vocabulary("Lesson 11", "laugh", "/lɑ:f/", "(adj) ccười; tiếng cười", "b");
        Vocabulary v85 = new Vocabulary("Lesson 11", "leader", "/´li:də/", "(n) người lãnh đạo, lãnh tụ", "b");
        Vocabulary v86 = new Vocabulary("Lesson 12", "machine", "/mə'ʃi:n/", "( n) máy, máy móc", "c");
        Vocabulary v87 = new Vocabulary("Lesson 12", "maintain", "/mein´tein/", "(v) giữ gìn, duy trì, bảo vệ", "a");
        Vocabulary v88 = new Vocabulary("Lesson 12", "major", "/ˈmeɪdʒər/", "(adj) lớn, nhiều hơn, trọng đại, chủ yếu", "b");
        Vocabulary v89 = new Vocabulary("Lesson 12", "manager", "/'mæniʤ/", "(v) quản lý, trông nom, điều khiển", "c");
        Vocabulary v90 = new Vocabulary("Lesson 12", "market", "/'mɑ:kit/", "(n) chợ, thị trường", "a");
        Vocabulary v91 = new Vocabulary("Lesson 13", "narrow", "/'nærou/", "(adj) hẹp, chật hẹp", "animation");
        Vocabulary v92 = new Vocabulary("Lesson 13", "national", "/'næʃən(ə)l/", "(n) quốc gia, dân tộc", "b");
        Vocabulary v93 = new Vocabulary("Lesson 13", "necessary", "/'nesəseri/ ", "(adj) cần, cần thiết, thiết yếu", "a");
        Vocabulary v94 = new Vocabulary("Lesson 13", "neighbour", "/'neibə/", "(n) hàng xóm", "b");
        Vocabulary v95 = new Vocabulary("Lesson 13", "noisy", "/´nɔizi/", "(adj) ồn ào, huyên náo", "b");
        Vocabulary v96 = new Vocabulary("Lesson 14", "offer", "/ˈkæpɪtl/", "( n/v) biếu, tặng, cho; sự trả giá", "c");
        Vocabulary v97 = new Vocabulary("Lesson 14", "office", "/'ɔfis/", "(n) cơ quan, văn phòng, bộ", "a");
        Vocabulary v98 = new Vocabulary("Lesson 14", "opinion", "/ə'pinjən/", "(n) ý kiến, quan điểm", "b");
        Vocabulary v99 = new Vocabulary("Lesson 14", "organize", "/´ɔ:gə¸naiz/", "(v) tổ chức, thiết lập", "c");
        Vocabulary v100 = new Vocabulary("Lesson 14", "overcome", "/ˌoʊvərˈkʌm/", "(v) thắng, chiến thắng, khắc phục", "a");
        Vocabulary v101 = new Vocabulary("Lesson 15", "page", "/peidʒ/", "( n) trang", "c");
        Vocabulary v102 = new Vocabulary("Lesson 15", "palace", "/ˈpælɪs/", "(n) cung điện, lâu đài", "a");
        Vocabulary v103 = new Vocabulary("Lesson 15", "party", "/ˈpɑrti/", "(n) tiệc, buổi liên hoan", "b");
        Vocabulary v104 = new Vocabulary("Lesson 15", "passport", "/´pa:spɔ:t/", "(n) hộ chiếu", "c");
        Vocabulary v105 = new Vocabulary("Lesson 15", "patient", "/'peiʃənt/", "(n) /  bệnh nhân; kiên nhẫn, nhẫn nại, bền chí", "a");
        Vocabulary v106 = new Vocabulary("Lesson 16", "capital", "/ˈkæpɪtl/", "( n/adj) thủ đô, tiền vốn; chủ yếu", "c");
        Vocabulary v107 = new Vocabulary("Lesson 16", "capture", "/'kæptʃə/", "(v/n) bắt giữ, bắt; sự bắt giữ", "a");
        Vocabulary v108 = new Vocabulary("Lesson 16", "combination", "/,kɔmbi'neiʃn/", "(n) sự kết hợp, sự phối hợp", "b");
        Vocabulary v109 = new Vocabulary("Lesson 16", "commission", "/kəˈmɪʃən/", "(n/v) hội đồng, ủy ban, sự ủy nhiệm", "c");
        Vocabulary v110 = new Vocabulary("Lesson 16", "complicate", "/'komplikeit/", "(v) làm phức tạp, rắc rối", "a");
        Vocabulary v111 = new Vocabulary("Lesson 17", "qualification", "/,kwalifi'keiSn/", "(n) phẩm chất, năng lực; khả năng chuyên môn", "c");
        Vocabulary v112 = new Vocabulary("Lesson 17", "qualify", "/'´kwɔli¸fai/", "(v) đủ khả năng, đủ tư cách, điều kiện", "a");
        Vocabulary v113 = new Vocabulary("Lesson 17", "quality", "/'kwɔliti/", "(n) chất lượng, phẩm chất", "b");
        Vocabulary v114 = new Vocabulary("Lesson 17", "quantity", "/ˈkwɒntɪti/", "(n) hlượng, số lượng", "c");
        Vocabulary v115 = new Vocabulary("Lesson 17", "question", "/ˈkwɛstʃən/", "(n) câu hỏi; hỏi, chất vấn", "a");
        Vocabulary v116 = new Vocabulary("Lesson 18", "rain", "/rein/", "(n/v) mưa, cơn mưa; mưa", "c");
        Vocabulary v117 = new Vocabulary("Lesson 18", "reality", "/ri:'æliti/", "(n) sự thật, thực tế, thực tại", "a");
        Vocabulary v118 = new Vocabulary("Lesson 18", "reason", "/'ri:zn/", "(n) lý do, lý lẽ", "b");
        Vocabulary v119 = new Vocabulary("Lesson 18", "reception", "/ri'sep∫n/", "(n) sự nhận, sự tiếp nhận, sự đón tiếp", "c");
        Vocabulary v120 = new Vocabulary("Lesson 18", "reduce", "/ri'dju:s/", "(v) giảm, giảm bớt", "a");
        Vocabulary v121 = new Vocabulary("Lesson 19", "safe", "/seif/", "(adj) an toàn, chắc chắn, đáng tin", "c");
        Vocabulary v122 = new Vocabulary("Lesson 19", "sailor", "/seilə/", "(n) thủy thủ", "a");
        Vocabulary v123 = new Vocabulary("Lesson 19", "satisfy", "/'sætisfai/", "(v) làm thỏa mãn, hài lòng", "b");
        Vocabulary v124 = new Vocabulary("Lesson 19", "scare", "/skɛə/", "(v) làm kinh hãi, sợ hãi, dọa; sự sợ hãi", "c");
        Vocabulary v125 = new Vocabulary("Lesson 19", "scheme", "/ski:m/", "(n) sự sắp xếp, sự phối hợp", "a");
        Vocabulary v126 = new Vocabulary("Lesson 20", "table", "/'teibl/", "( n) cái bàn", "c");
        Vocabulary v127 = new Vocabulary("Lesson 20", "task", "/tɑːsk/", "(n) nhiệm vụ, nghĩa vụ", "a");
        Vocabulary v128 = new Vocabulary("Lesson 20", "technology", "/tek'nɔlədʤi/", "(n) kỹ thuật học, công nghệ học", "b");
        Vocabulary v129 = new Vocabulary("Lesson 20", "together", "/tə'geðə/", "(adv) cùng nhau, cùng với", "c");
        Vocabulary v130 = new Vocabulary("Lesson 20", "towards", "/tə´wɔ:dz/", "(prep) theo hướng, về hướng", "a");
        Vocabulary v131 = new Vocabulary("Lesson 21", "ultimate", "/ˈʌltəmɪt/", "(adj) cuối cùng, sau cùng", "c");
        Vocabulary v132 = new Vocabulary("Lesson 21", "umbrella", "/ʌm'brelə/", "(n) ô, dù", "a");
        Vocabulary v133 = new Vocabulary("Lesson 21", "understanding", "/ˌʌndərˈstændɪŋ/", "(n) trí tuệ, sự hiểu biết", "b");
        Vocabulary v134 = new Vocabulary("Lesson 21", "uniform", "/ˈjunəˌfɔrm/", "(n/adj) đồng phục; đều, giống nhau", "c");
        Vocabulary v135 = new Vocabulary("Lesson 21", "university", "/¸ju:ni´və:siti/", "(n) trường đại họci", "a");
        Vocabulary v136 = new Vocabulary("Lesson 22", "valid", "/'vælɪd/", "(adj) chắc chắn, hiệu quả, hợp lý", "c");
        Vocabulary v137 = new Vocabulary("Lesson 22", "value", "/'vælju:/", "(n/v) giá trị, ước tính, định giá", "a");
        Vocabulary v138 = new Vocabulary("Lesson 22", "venture", "/'ventʃə/", "(n/v) sự án kinh doanh, công việc kinh doanh", "b");
        Vocabulary v139 = new Vocabulary("Lesson 22", "victory ", "/'viktəri/", "(n) chiến thắng", "c");
        Vocabulary v140 = new Vocabulary("Lesson 22", "visitor", "/'vizitə/", "(n) khách, du khách", "a");
        Vocabulary v141 = new Vocabulary("Lesson 23", "wage", "/weiʤ/", "(n) tiền lương, tiền công", "c");
        Vocabulary v142 = new Vocabulary("Lesson 23", "wander", "/'wɔndə/", "(v/n) đi lang thang; sự đi lang thang", "a");
        Vocabulary v143 = new Vocabulary("Lesson 23", "wave", "/weɪv/", "(n/v) sóng, gợn nước; gợn sóng, uốn thành sóng", "b");
        Vocabulary v144 = new Vocabulary("Lesson 23", "weather", "/'weθə/", "(n) thời tiết", "c");
        Vocabulary v145 = new Vocabulary("Lesson 23", "wind", "/wind/", "(n) gió", "a");
        Vocabulary v146 = new Vocabulary("Lesson 24", "yellow", "/'jelou/", "(adj/n) vàng; màu vàng", "c");
        Vocabulary v147 = new Vocabulary("Lesson 24", "yesterday", "/'jestədei/", "(n) hôm qua", "a");
        Vocabulary v148 = new Vocabulary("Lesson 24", "young", "/jʌɳ/", "(adj) trẻ, trẻ tuổi, thanh niên", "b");
        Vocabulary v149 = new Vocabulary("Lesson 24", "yawn", "/jɔ:n/", "(v) há miệng", "c");
        Vocabulary v150 = new Vocabulary("Lesson 24", "youth", "/ju:θ/ ", "(n) tuổi trẻ, tuổi xuân, tuổi thanh niên", "a");
        Vocabulary v151 = new Vocabulary("Lesson 25", "wish", "/wi∫/", "(v/n) ước, mong muốn; sự mong ước", "c");
        Vocabulary v152 = new Vocabulary("Lesson 25", "within", "/wɪθaʊt/", "(prep) không, không có", "a");
        Vocabulary v153 = new Vocabulary("Lesson 25", "witness", "/'witnis/ ", "(n) sự làm chứng, bằng chứng", "b");
        Vocabulary v154 = new Vocabulary("Lesson 25", "woman", "/'wʊmən/", "(n) đàn bà, phụ nữ", "c");
        Vocabulary v155 = new Vocabulary("Lesson 25", "wood", "/wud/", "(c) gỗ", "a");
        Vocabulary v156 = new Vocabulary("Lesson 26", "work", "/wɜ:k/", "(v) làm việc, sự làm việc", "c");
        Vocabulary v157 = new Vocabulary("Lesson 26", "wrist", "/rist/", "(n) cổ tay", "a");
        Vocabulary v158 = new Vocabulary("Lesson 26", "worried", "/´wʌrid/", "(adj) bồn chồn, lo nghĩ, tỏ ra lo lắng", "b");
        Vocabulary v159 = new Vocabulary("Lesson 26", "wool", "/wul/", "(n) len", "c");
        Vocabulary v160 = new Vocabulary("Lesson 26", "world", "/wɜ:ld/", "(n) thế giới", "Heal the world.");
        database.insertVol(v1);
        database.insertVol(v2);
        database.insertVol(v3);
        database.insertVol(v4);
        database.insertVol(v5);
        database.insertVol(v6);
        database.insertVol(v7);
        database.insertVol(v8);
        database.insertVol(v9);
        database.insertVol(v10);
        database.insertVol(v11);
        database.insertVol(v12);
        database.insertVol(v13);
        database.insertVol(v14);
        database.insertVol(v15);
        database.insertVol(v16);
        database.insertVol(v17);
        database.insertVol(v18);
        database.insertVol(v19);
        database.insertVol(v20);
        database.insertVol(v21);
        database.insertVol(v22);
        database.insertVol(v23);
        database.insertVol(v24);
        database.insertVol(v25);
        database.insertVol(v26);
        database.insertVol(v27);
        database.insertVol(v28);
        database.insertVol(v29);
        database.insertVol(v30);
        database.insertVol(v21);
        database.insertVol(v22);
        database.insertVol(v23);
        database.insertVol(v24);
        database.insertVol(v25);
        database.insertVol(v26);
        database.insertVol(v27);
        database.insertVol(v28);
        database.insertVol(v29);
        database.insertVol(v30);
        database.insertVol(v21);
        database.insertVol(v22);
        database.insertVol(v23);
        database.insertVol(v24);
        database.insertVol(v25);
        database.insertVol(v26);
        database.insertVol(v27);
        database.insertVol(v28);
        database.insertVol(v29);
        database.insertVol(v30);
        database.insertVol(v21);
        database.insertVol(v22);
        database.insertVol(v23);
        database.insertVol(v24);
        database.insertVol(v25);
        database.insertVol(v26);
        database.insertVol(v27);
        database.insertVol(v28);
        database.insertVol(v29);
        database.insertVol(v30);
        database.insertVol(v31);
        database.insertVol(v32);
        database.insertVol(v33);
        database.insertVol(v34);
        database.insertVol(v35);
        database.insertVol(v36);
        database.insertVol(v37);
        database.insertVol(v38);
        database.insertVol(v39);
        database.insertVol(v40);
        database.insertVol(v41);
        database.insertVol(v42);
        database.insertVol(v43);
        database.insertVol(v44);
        database.insertVol(v45);
        database.insertVol(v46);
        database.insertVol(v47);
        database.insertVol(v48);
        database.insertVol(v49);
        database.insertVol(v50);
        database.insertVol(v51);
        database.insertVol(v52);
        database.insertVol(v53);
        database.insertVol(v54);
        database.insertVol(v55);
        database.insertVol(v56);
        database.insertVol(v57);
        database.insertVol(v58);
        database.insertVol(v59);
        database.insertVol(v60);
        database.insertVol(v61);
        database.insertVol(v62);
        database.insertVol(v63);
        database.insertVol(v64);
        database.insertVol(v65);
        database.insertVol(v66);
        database.insertVol(v67);
        database.insertVol(v68);
        database.insertVol(v69);
        database.insertVol(v70);
        database.insertVol(v71);
        database.insertVol(v72);
        database.insertVol(v73);
        database.insertVol(v74);
        database.insertVol(v75);
        database.insertVol(v76);
        database.insertVol(v77);
        database.insertVol(v78);
        database.insertVol(v79);
        database.insertVol(v80);
        database.insertVol(v81);
        database.insertVol(v82);
        database.insertVol(v83);
        database.insertVol(v84);
        database.insertVol(v85);
        database.insertVol(v86);
        database.insertVol(v87);
        database.insertVol(v88);
        database.insertVol(v89);
        database.insertVol(v90);
        database.insertVol(v91);
        database.insertVol(v92);
        database.insertVol(v93);
        database.insertVol(v94);
        database.insertVol(v95);
        database.insertVol(v96);
        database.insertVol(v97);
        database.insertVol(v98);
        database.insertVol(v99);
        database.insertVol(v100);
        database.insertVol(v101);
        database.insertVol(v102);
        database.insertVol(v103);
        database.insertVol(v104);
        database.insertVol(v105);
        database.insertVol(v106);
        database.insertVol(v107);
        database.insertVol(v108);
        database.insertVol(v109);
        database.insertVol(v110);
        database.insertVol(v111);
        database.insertVol(v112);
        database.insertVol(v113);
        database.insertVol(v114);
        database.insertVol(v115);
        database.insertVol(v116);
        database.insertVol(v117);
        database.insertVol(v118);
        database.insertVol(v119);
        database.insertVol(v120);
        database.insertVol(v121);
        database.insertVol(v122);
        database.insertVol(v123);
        database.insertVol(v124);
        database.insertVol(v125);
        database.insertVol(v126);
        database.insertVol(v127);
        database.insertVol(v128);
        database.insertVol(v129);
        database.insertVol(v130);
        database.insertVol(v131);
        database.insertVol(v132);
        database.insertVol(v133);
        database.insertVol(v134);
        database.insertVol(v135);
        database.insertVol(v136);
        database.insertVol(v137);
        database.insertVol(v138);
        database.insertVol(v139);
        database.insertVol(v140);
        database.insertVol(v141);
        database.insertVol(v142);
        database.insertVol(v143);
        database.insertVol(v144);
        database.insertVol(v145);
        database.insertVol(v146);
        database.insertVol(v147);
        database.insertVol(v148);
        database.insertVol(v149);
        database.insertVol(v150);
        database.insertVol(v151);
        database.insertVol(v152);
        database.insertVol(v153);
        database.insertVol(v154);
        database.insertVol(v155);
        database.insertVol(v156);
        database.insertVol(v157);
        database.insertVol(v158);
        database.insertVol(v159);
        database.insertVol(v160);

    }

    void addDbTest() {
        Test test1 = new Test("English Test 1", "The football fans are very ……………", "excite", "exciting", "excited", "be excited", "excited");
        Test test2 = new Test("English Test 1", "The play was very …………… and he became very rich", "success", "successful", "successfully", "succeed", "successful");
        Test test3 = new Test("English Test 1", "Louis Braille never knew of the importance of his ……………", "invent", "invention", "invented", "inventing", "invention");
        Test test4 = new Test("English Test 1", "She’s …………… about her cat. She didn’t eat her food yesterday", "happy", "excited", "worried", "angry", "worried");
        Test test5 = new Test("English Test 1", "They …………… my house and said nothing.", "go", "left", "leave", "went", "left");
        Test test6 = new Test("English Test 1", "I was upset because my boss …………… nothing to me.", "pay", "paid", "pays", "to pay", "paid");
        Test test7 = new Test("English Test 1", " …………… you like anything to drink?", "Do", "Are", "Would", "Can", "Would");
        Test test8 = new Test("English Test 1", "There is …………… crisps in the picnic bag", "a box of", "a tin of", "a jar of", "a packet of", "a packet of");
        Test test9 = new Test("English Test 1", "Can I have a …………… of baked beans, please?", "bottle", "tin", "bowl", "bar", "tin");
        Test test10 = new Test("English Test 1", "I would like to …………… a single room, please", "want", "book", "rent", "buy", "book");
        Test test11 = new Test("English Test 2", "She has an …………… job.", "usually", "unusually", "unusual", "usual", "unusual");
        Test test12 = new Test("English Test 2", "They invited …………… dinner with them", "us for having", "that we have", "us to have", "our having", "us to have");
        Test test13 = new Test("English Test 2", "She received 15 …………… from her friends", "birthdays card", "birthdays cards", "birthday’s cards", "birthday cards", "birthday cards");
        Test test14 = new Test("English Test 2", "Most of the students are………………..to pass the exam.", "enough good", "too good", "good enough", "very good", "good enough");
        Test test15 = new Test("English Test 2", "Some children eat …………. candy.", "too", "too many", "too much", "many", "too much");
        Test test16 = new Test("English Test 2", "Can you touch your left ear ……….your left shoulder?", "to", "within", "with", "up to", "with");
        Test test17 = new Test("English Test 2", "When she relaxes, she often sits ………..her legs straight out in front of her.", "from", "with", "at", "off", "with");
        Test test18 = new Test("English Test 2", "The house is …………..small for us to live in.", "invent", "invention", "invented", "inventing", "invention");
        Test test19 = new Test("English Test 2", "Are they ……….now? I smell something burn in the kitchen", "cook", "cooking", "cooks", "cooked", "cooking");
        Test test20 = new Test("English Test 2", " …………… they dancing at the moment?", "Do", "Are", "Did", "Can", "Are");
        Test test21 = new Test("English Test 3", "Be quiet! My baby……………", "sleep", "sleeps", "is sleeping", "slept", "is sleeping");
        Test test22 = new Test("English Test 3", "Don't forget to bring an umbrella. It …………… so heavily", "rain", "raining", "is raining", "rained", "is raining");
        Test test23 = new Test("English Test 3", "She …………… very beautiful but many boys like her", "looks", "looks like", "doesn't look", "doesn't look like", "doesn't look");
        Test test24 = new Test("English Test 3", "She is wearing an expensive gold …………… on her wrist ", "ring", "chain", "bracelet", "earrings", "bracelet");
        Test test25 = new Test("English Test 3", "He often wears …………… on hot summer days", "socks", "shorts", "coat", "jacket", "shorts");
        Test test26 = new Test("English Test 3", "Trainers are my favourite …………… ", "footwear", "underwear", "accessories ", "clothes", "footwear");
        Test test27 = new Test("English Test 3", "Look! It is …………… ", "raining (1)", "going to rain(2)", "rained", "Both (1) & (2) are correct", "Both (1) & (2) are correct");
        Test test28 = new Test("English Test 3", "Turn on CNN to update the world ……………", "news", "new", "soap opera", "live show", "news");
        Test test29 = new Test("English Test 3", "I often watch …………… after the news to know about the weather tomorrow", "a documentary", "the weather", "soap opera", "reality TV", "the weather");
        Test test30 = new Test("English Test 3", "My son loves watching …………… about animals on Discoveries channel ", "films", "news", "documentaries", "shows ", "documentaries");
        Test test31 = new Test("English Test 4", "I really like …………… on ESPN and True Sports.", "reality TV ", "game show ", "films", "sport programmes", "sport programmes");
        Test test32 = new Test("English Test 4", "It often takes me at least 10 minutes every morning to find my …………… I cannot see anything without them.", "keys", "glasses", "mobile phone", "TV remote", "glasses");
        Test test33 = new Test("English Test 4", "It was …………… film I have ever seen", "good", "best", "the best", "the good", "the best");
        Test test34 = new Test("English Test 4", "Peter sang …………… than all the others.", "loudly", "louder", "more loudly", "loudest", "louder");
        Test test35 = new Test("English Test 4", "The holiday was not …………… the one we had last year.", "as expensive as", "more expensive", "expensive", "the most expensive", "as expensive as");
        Test test36 = new Test("English Test 4", "She's a good student. She is …………… than the others", "careful", "more careful", "more carefully", "as careful as", "more careful");
        Test test37 = new Test("English Test 4", "Would you please be …………… please? I am trying to sleep", "quietly", "more quietly", "more quiet", "quieter", "quieter");
        Test test38 = new Test("English Test 4", "My mother wakes up …………… than me", "early", "more early", "earlier", "earliest", "earlier");
        Test test39 = new Test("English Test 4", "Do you earn a good …………… in that company?", "salary", "money", "job", "career", "salary");
        Test test40 = new Test("English Test 4", "Have you ever paid by …………… card?", "student", "ID", "credit", "phone", "credit");
        Test test41 = new Test("English Test 5", "Children usually …………their feet when they get angry.", "Shrug", "Bend", "Stamp", "Hit", "Stamp");
        Test test42 = new Test("English Test 5", "Some rude people often click their ……….. to call waiters in the restaurant.", "legs", "toes", "fingers", "hands", "fingers");
        Test test43 = new Test("English Test 5", "The river is ......... enough for big ships to sail up to the part of Moscow.", "deep", "far", "small", "Narrow ", "deep");
        Test test44 = new Test("English Test 5", "She has no money now because she spent so .......... money last month.", "many", "much", "little", "few", "much");
        Test test45 = new Test("English Test 5", "You shouldn’t …………. your legs when working with your computer.", "Cross", "Nod", "Clap", "stamp", "Cross");
        Test test46 = new Test("English Test 5", "She is too ……….with her work, so she doesn’t have time to go out with her friends", "bored", "busy", "fed up", "tired", "busy");
        Test test47 = new Test("English Test 5", "Don't …………. the door. The paint is still wet.", "Touch", "leave", "keep off", "watch", "Touch");
        Test test48 = new Test("English Test 5", "She is a dancer, so you should buy a pair of ………..shoes as a present for her birthday.", "dance", "dancing", "dances", "dancer’s", "dancing");
        Test test49 = new Test("English Test 5", "She learnt by ………………. all these long poems.", "head", "heart", "stomach", "Chest", "head");
        Test test50 = new Test("English Test 5", "Penguins often stay on pack ice and never set ………..on land.", "toes", "Wings", "legs", "foot", "foot");
        Test test51 = new Test("English Test 6", "She eats …………..and drink three litres of water a day.", "health", "healthy", "healthily", "healthly", "healthily");
        Test test52 = new Test("English Test 6", "The play was very …………… and he became very rich", "success", "successful", "successfully", "succeed", "successful");
        Test test53 = new Test("English Test 6", "Louis Braille never knew of the importance of his ……………", "invent", "invention", "invented", "inventing", "invention");
        Test test54 = new Test("English Test 6", "She’s …………… about her cat. She didn’t eat her food yesterday", "happy", "excited", "worried", "angry", "worried");
        Test test55 = new Test("English Test 6", "They …………… my house and said nothing.", "go", "left", "leave", "went", "left");
        Test test56 = new Test("English Test 6", "The football fans are very ……………", "excite", "exciting", "excited", "be excited", "excited");
        Test test57 = new Test("English Test 6", "The play was very …………… and he became very rich", "success", "successful", "successfully", "succeed", "successful");
        Test test58 = new Test("English Test 6", "Louis Braille never knew of the importance of his ……………", "invent", "invention", "invented", "inventing", "invention");
        Test test59 = new Test("English Test 6", "She’s …………… about her cat. She didn’t eat her food yesterday", "happy", "excited", "worried", "angry", "worried");
        Test test60 = new Test("English Test 6", "They …………… my house and said nothing.", "go", "left", "leave", "went", "left");
        Test test61 = new Test("English Test 7", "The football fans are very ……………", "excite", "exciting", "excited", "be excited", "excited");
        Test test62 = new Test("English Test 7", "The play was very …………… and he became very rich", "success", "successful", "successfully", "succeed", "successful");
        Test test63 = new Test("English Test 7", "Louis Braille never knew of the importance of his ……………", "invent", "invention", "invented", "inventing", "invention");
        Test test64 = new Test("English Test 7", "She’s …………… about her cat. She didn’t eat her food yesterday", "happy", "excited", "worried", "angry", "worried");
        Test test65 = new Test("English Test 7", "They …………… my house and said nothing.", "go", "left", "leave", "went", "left");
        Test test66 = new Test("English Test 7", "The football fans are very ……………", "excite", "exciting", "excited", "be excited", "excited");
        Test test67 = new Test("English Test 7", "The play was very …………… and he became very rich", "success", "successful", "successfully", "succeed", "successful");
        Test test68 = new Test("English Test 7", "Louis Braille never knew of the importance of his ……………", "invent", "invention", "invented", "inventing", "invention");
        Test test69 = new Test("English Test 7", "She’s …………… about her cat. She didn’t eat her food yesterday", "happy", "excited", "worried", "angry", "worried");
        Test test70 = new Test("English Test 7", "They …………… my house and said nothing.", "go", "left", "leave", "went", "left");
        Test test71 = new Test("English Test 8", "The Ice hotel …………..on the shores of  the Torn river in the old village of Jukkasijarvi, Sweden.", "Situate", "situated", "is situate", "is situated", "is situated");
        Test test72 = new Test("English Test 8", "When he returned home, he found the door………….", "unlocking", "to be unlocked", "unlocked", "have unlocked", "unlocked");
        Test test73 = new Test("English Test 8", "Hot weather ……………..", "makes me feeling uncomfortable", "makes me to feel uncomfortable", "makes me feel uncomfortable", "makes me to have felt uncomfortable", "makes me feel uncomfortable");
        Test test74 = new Test("English Test 8", "The robber ………….three days ago.", "Arrested", "was arrested", "arrest", "is arrested", "was arrested");
        Test test75 = new Test("English Test 8", "Humphrey Bogart ……..on Christmas day in A999.", "was born", "was borned", "born", "borned", "was born");
        Test test76 = new Test("English Test 8", "Students ……………to wear uniforms at all times.", "Is required", "are required", "required", "require", "are required");
        Test test77 = new Test("English Test 8", "Lunch ………………..when we arrived.", "Is served", "was served", "was being served", "served", "was being served");
        Test test78 = new Test("English Test 8", "Lectures and posted on the Internet.", "is recorded", "are recorded", "recorded", "record", "are recorded");
        Test test79 = new Test("English Test 8", "Portuguese…………………….. in this village.", "speak", "spoke", "are spoke", "has always been spoken", "has always been spoken");
        Test test80 = new Test("English Test 8", "The instructions ………………….", "have been changed", "has been changed", "changed", "is changed", "have been changed");
        Test test81 = new Test("English Test 9", "Casual clothes ………………………….", "must worn", "must not be worn", "is worn", "must wear", "must not be worn");
        Test test82 = new Test("English Test 9", "The test_english …………………. at five o'clock this afternoon.", "is given", "will give", "will given", "will be given", "will be given");
        Test test83 = new Test("English Test 9", "We ………………….to wait here.", "were told", "told", "was told", "was telled", "were told");
        Test test84 = new Test("English Test 9", "My keys………….in the street last Monday.", "found", "find", "were founded", "were found", "were found");
        Test test85 = new Test("English Test 9", "The exams ……….by the teachers this afternoon.", "marked", "was marked", "were marked", "were mark", "were marked");
        Test test86 = new Test("English Test 9", "She ……………by the accident.", "shocked", "was shocked", "were shocked", "shock", "was shocked");
        Test test87 = new Test("English Test 9", "The robbers ……………five hours later.", "arrested", "was arrested", "were arrested", " are arrested", "were arrested");
        Test test88 = new Test("English Test 9", "The flight ………….because of the storm.", "was cancelled", "were cancelled", "cancelled", "cancel", "was cancelled");
        Test test89 = new Test("English Test 9", "I………….where I bought my clothes.", "asked", "was asked", "ask", "were asked", "was asked");
        Test test90 = new Test("English Test 9", "The injured people ………to the hospital immediately.", "was take", "was taken", "taken", "were taken", "were taken");
        Test test91 = new Test("English Test 10", "Mike ………….a guitar on his birthday.", "Is given", "was given", "will given", "Give", "was given");
        Test test92 = new Test("English Test 10", " I think, my mother………………..this CD. ", "will like", "like", "Is  going to like", "liked", "will like");
        Test test93 = new Test("English Test 10", "Just a moment. I…………….you with the bags.", "am going to help", "will help", "help", "helps", "will help");
        Test test94 = new Test("English Test 10", "The beds in the ice hotel is covered “boc”………….reindeer  skins.", "on", "in", "under", "with", "with");
        Test test95 = new Test("English Test 10", "The drinks in the Ice hotel are served in glasses made……….ice.", "of", "in", "on", "at", "of");
        Test test96 = new Test("English Test 10", "The first Ice hotel …………..in A990.", "is constructed", "are constructed", "was constructed", "were constructed", "was constructed");
        Test test97 = new Test("English Test 10", "I think we………….have a lot of snow next winter.", "is going to", "are going to", "will be", "will", "will");
        Test test98 = new Test("English Test 10", "……… you attended any parties last week?", "Are", "were", "was", "is", "were");
        Test test99 = new Test("English Test 10", "Guests………….to the hotel by a submarine.", "Is taken", "are taken", "take", "took", "are taken");
        Test test100 = new Test("English Test 10", "These cars…………… in Japan.  ", "are produced", "is produced", "produce", "produced", "are produced");
        Test test101 = new Test("English Test 11", "Lots of houses……………… by the earthquake last year.", "was destroyed", "is destroyed", "were destroyed", "destroyed", "were destroyed");
        Test test102 = new Test("English Test 11", "………………your house built before 1980?", "When", "Where", "were", "was", "was");
        Test test103 = new Test("English Test 11", "Were your name………….in the same way in English?", "spelt", "spelled", "spelling", "spell", "spelt");
        Test test104 = new Test("English Test 11", "Somebody …………..the first Ice hotel in 1990.", "construct", "constructed", "was constructed", "were constructed", "constructed");
        Test test105 = new Test("English Test 11", "I think we………have a lot of snow next winter.", "is going to", "going to", "are going to", "will", "will");
        Test test106 = new Test("English Test 11", "When the frog ……..by a beautiful princess, it would change into a handsome prince.", "kissed", "was kiss", "was kissed", "were kissed", "was kissed");
        Test test107 = new Test("English Test 11", "The dinner …………..at 6.C0 in the afternoon.", "will be served", "be served", "served", "will served", "will be served");
        Test test108 = new Test("English Test 11", "She …………..by a strange noise, but she did not get up.", "wake up", "woke up", "woken up", "was woken up", "was woken up");
        Test test109 = new Test("English Test 11", " Were the children ……….to the zoo last Sunday?", "take", "took", "taken", "take", "taken");
        Test test110 = new Test("English Test 11", "That man was……………….  by lightning twice in the past year", "Beaten", "struck", "Strike", "stroke", "Beaten");
        Test test111 = new Test("English Test 12", "A…………is a long period without any rain.", "Draft", "Drought ", "dry", "pollution", "Drought");
        Test test112 = new Test("English Test 12", "We're in the middle of a heat-……... It has been very hot for two weeks.", "Wave", "Streak", "Flow", "waved", "wave");
        Test test113 = new Test("English Test 12", "Another word for cloudy is ……….. ", "clouded", "crowded", "Freezing", "fog", "Freezing");
        Test test114 = new Test("English Test 12", "The…………on the weather map are in Celsius degrees.", "weather", "climate", "season", "temperatures", "temperatures");
        Test test115 = new Test("English Test 12", "Many homes were ……….. by the hurricane “bao”.", "destructed", "destroyed", "ruined", "built", "destroyed");
        Test test116 = new Test("English Test 12", "This is similar to fog but not so thick and usually seen in the morning", "cloud", "smog", "Mist", "Storm", "Mist");
        Test test117 = new Test("English Test 12", "A spectacular electric discharge produced in a storm", "Lightning", "shooting stars", "Thunder", "bomb", "Lightning");
        Test test118 = new Test("English Test 12", "To describe sharp and unpleasant cold.", "boiling", "Chilly", "Mild", "cold", "Chilly");
        Test test119 = new Test("English Test 12", "The weather in winter in Vietnam is very ………", "hot", "warm", "cool", "cold", "cold");
        Test test120 = new Test("English Test 12", "The South has two main seasons: the wet and the …….. ", "rainy", "sunny", "dry", "drought", "dry");
        Test test121 = new Test("English Test 13", "It………be cloudy in the afternoon and there…probably be rain later on.", "is going to, is going to", "is going to, will", "will, is going to", "will, will", "will, will");
        Test test122 = new Test("English Test 13", "A period of two weeks is called a…………", "half a week ", "midnight", "midday", "Fortnight", "Fortnight");
        Test test123 = new Test("English Test 13", "In the West, it will be very windy, with a ……..of storm", "possible", "possibly", "possibility", "possibiler", "possibility");
        Test test124 = new Test("English Test 13", "All the latest……………was used to build the Neuschwanstein Castle.", "Techniques", "Technological", "Technology", "Technologically", "Technological");
        Test test125 = new Test("English Test 13", "Later, the castle was opened as a tourist ……….", "attraction", "attractive", "attractiveness", "attracted", "attraction");
        Test test126 = new Test("English Test 13", "The walls of the Poseidon Palace was made of……glass.", "special", "specially", "specialty", "specialised", "special");
        Test test127 = new Test("English Test 13", "The castle was designed by a theatre………", "designing", "designer", "designed", "design", "designer");
        Test test128 = new Test("English Test 13", "The computer is the most wonderful……in the B0th century.", "invent", "invented", "invention", "inventor", "invention");
        Test test129 = new Test("English Test 13", "Tom, it’s raining heavily. Don’t play …….the rain.", "under", "in", "through", "on", "in");
        Test test130 = new Test("English Test 13", "In Spring, the Ice hotel melts away and………..in the river.", "appears", "appeared", "disappears", "disappeared", "disappears");
        Test test131 = new Test("English Test 14", "The hottest season in the year in Vietnam is………….", "spring", "autumn", "winter", "summer", "summer");
        Test test132 = new Test("English Test 14", "Leaves often fall down in the ………………. ", "autumn", "winter", "summer", "spring", "autumn");
        Test test133 = new Test("English Test 14", "It looks like the sky is………………..  up. It's going to be a beautiful day.", "clearing", "shining", "cleaning", "Refreshing", "clearing");
        Test test134 = new Test("English Test 14", "Was it cold in Canada? Yes, it was B0……………  zero.", "under", "Below", "at", "on", "Below");
        Test test135 = new Test("English Test 14", "Summers in states like Tennessee are very hot and very ……….", "Humidity", "Humid", "Humidify", "Humidify", "Humid");
        Test test136 = new Test("English Test 14", "The coastal areas of California have an………. climate.", "Ideally", "Idea", "Ideal", "Ideality", "Ideal");
        Test test137 = new Test("English Test 14", "Did you check the weather……….  for tomorrow? Is it going to rain?", "Foreplay", "climate", "news", "Forecast", "Forecast ");
        Test test138 = new Test("English Test 14", "What's the weather ………………. today?", "like", "liked", "most like", "liker", "like");
        Test test139 = new Test("English Test 14", "It was cold in the morning, but it…………………… up by the afternoon.", "warmed", "heated", "hot", "heat", "warmed");
        Test test140 = new Test("English Test 14", "It's very cold. It's…………", "Freezing", "Frozen", "very cool", "Icy", "Frozen");
        Test test141 = new Test("English Test 15", "It was so ……………outside that my hat was blown off my head.", "wind", "windy", "winds", "winded", "windy");
        Test test142 = new Test("English Test 15", "Don't go outside! You could get……………  by lightning!", "strikes", "stroke", "struck", "striked", "struck");
        Test test143 = new Test("English Test 15", "People in the south of England will have a nice day with a lot of ………", "sun", "sunny", "shine", "Sunshine", "Sunshine");
        Test test144 = new Test("English Test 15", "This word means light rain that falls for a brief time.", "Sleeting", "a downpour", "a shower ", "storm", "a shower");
        Test test145 = new Test("English Test 15", "There are many dark clouds………..the sky.", "under", "on", "below", "in", "in");
        Test test146 = new Test("English Test 15", "There are a lot of showers in………in Vietnam.", "winter", "spring", "summer", "autumn", "summer");
        Test test147 = new Test("English Test 15", "The fog will soon ….. and it will be sunny later with temperature of around C", "appear", "appears", "disappears", "disappear", "disappear");
        Test test148 = new Test("English Test 15", "The…………difficult of part of the race is Eagle Mountain.", "most", "least", "last", "less", "most");
        Test test149 = new Test("English Test 15", "You can not ……how cold it is.", "Imaginable", "Imagination", "imagining", "imagineimagine", "imagine");
        Test test150 = new Test("English Test 15", "Tomorrow will be ……….", "sun", "shine", "sunny", "sunned", "sunny");
        Test test151 = new Test("English Test 16", "Winter in the North of Vietnam is………", "coldy", "cold", "cool", "cooly", "cold");
        Test test152 = new Test("English Test 16", "I still ………………. when the stewardess came to tell us that we …………. Olympus.", "was sleeping, passed", "slept, passed", "slept, was passing", "was sleeping, was passing", "was sleeping, passed ");
        Test test153 = new Test("English Test 16", "While Tom …………. the dinner, the phone ………….", "was cooking, is phoning", "was cooking, are phoning", "was cooking, were phoning", "was cooking, was phoning", "was cooking, was phoning");
        Test test154 = new Test("English Test 16", "The police are looking……………………a tall, black man who was seen standing outside the bank just before the robbery took place.", "In", "at", "for", "after", "for");
        Test test155 = new Test("English Test 16", "……………. television when I arrived?", "was you watching", "were you watching", "are you watching", "is you watching", "were you watching");
        Test test156 = new Test("English Test 16", "Ann was waiting for me at home when I ………… yesterday.", "arrived", "arrive", "arrives", "was arriving", "arrived");
        Test test157 = new Test("English Test 16", "I ……………. a plate last night. I was doing the washing up.", "breaked", "broked", "broke", "broken", "broke");
        Test test158 = new Test("English Test 16", "I saw Carol at the party. She ……… a really beautiful dress.", "was wearing", "is wearing", "were wearing", "are wearing", "was wearing");
        Test test159 = new Test("English Test 16", "In the end, I apologized………my friends.", "for", "with", "at", "to", "to");
        Test test160 = new Test("English Test 16", "We arrived…………………….Gorzosw at C.C0 in the morning.", "At", "in", "on", "for", "in");
        Test test161 = new Test("English Test 17", "While Mary was cleaning her flat, her husband…………..", "sleep", "slept", "was sleeping", "is sleeping", "was sleeping");
        Test test162 = new Test("English Test 17", "What………at 9 a.m yesterday?", "were you doing", "did you do", "were you do", "are you doing", "were you doing");
        Test test163 = new Test("English Test 17", "He was sitting on the beach when he ……..a noise.", "was hearing", "heard", "had heard", "hears", "heard");
        Test test164 = new Test("English Test 17", "He behaved in a……………..manner", "friend", "friends", "friendly", "friended", "friendly");
        Test test165 = new Test("English Test 17", "He is ……………….. in what he does.", "successed", "Successful", "successfully", "succeeded", "Successful");
        Test test166 = new Test("English Test 17", "I have………………. finished reading the book.", "nearly", "nearer", "nearest", "near", "nearly");
        Test test167 = new Test("English Test 17", "Yesterday at six I ………………….. dinner.", "was prepare", "was preparing", "were preparing", "preparing", "was preparing");
        Test test168 = new Test("English Test 17", "The kids…………….in the garden when it suddenly began to rain", "playing", "was playing", "were play", "were playing", "were playing");
        Test test169 = new Test("English Test 17", "Most of the time we …………………in the park. ", "sit", "sat", "was sitting", "were sitting", "sat");
        Test test170 = new Test("English Test 17", "I ……… the guitar when he came home. ", "practised", "practising", "was practising", "were practising", "was practising");
        Test test171 = new Test("English Test 18", "I got a postcard ………Hermione", "about", "off", "from", "to", "from");
        Test test172 = new Test("English Test 18", "……………first, I could hardly believe them", "in", "At", "By", "For", "At");
        Test test173 = new Test("English Test 18", "Jane cut………… the arms and legs of her husband’s suit with a scissor.", "off", "out", "of", "up", "off");
        Test test174 = new Test("English Test 18", "I arrived…………appointment very early.", "in", "at", "on", "for", "for");
        Test test175 = new Test("English Test 18", "She arrived………………………..Manchester for the celebrations.", "at", "in", "on", "to", "in");
        Test test176 = new Test("English Test 18", "Let's meet………………………..seven o'clock.", "in", "on", "about", "at", "at");
        Test test177 = new Test("English Test 18", "I didn't see Hermione…………………..the party on Saturday.", "at", "in", "on", "onto", "at");
        Test test178 = new Test("English Test 18", "George fell off the ladder while he …………. the ceiling.", "was painting", "is painting", "are painting", "were painting", "was painting");
        Test test179 = new Test("English Test 18", "We are standing …………. his house waiting for him.", "inside", "outside", "in", "on", "outside");
        Test test180 = new Test("English Test 18", "She said……..the prince, “I want to be your wife. Will you marry me?”", "at", "with", "to", "about", "to");
        Test test181 = new Test("English Test 19", "The witch looked at the prince in the eyes, and kissed him…….. the lips.", "in", "at", "under", "on", "on");
        Test test182 = new Test("English Test 19", "……………, I saw him walking to the church.", "in", "on", "about", "at", "about");
        Test test183 = new Test("English Test 19", "Were they looking at the T.V………..?", "at the moment", "now", "at 9 o’clock", " at 9 p.m yesterday", " at 9 p.m yesterday");
        Test test184 = new Test("English Test 19", "My partner and I ………to Salanika by air yesterday morning.", "go", "goed", "went", "goes", "went");
        Test test185 = new Test("English Test 19", "He plays the guitar………….", "terrible", "terribly", "good", "beautiful", "terribly");
        Test test186 = new Test("English Test 19", "They dance the cha-cha-cha ……………………..", "beautiful", "beauty", "beautifully", "beautified", "beautifully");
        Test test187 = new Test("English Test 19", "She planned their trip to Greece very……………………..", "carefully", "careful", "careless", "care", "carefully");
        Test test188 = new Test("English Test 19", "……..you living in the same house this time last year?", "are", "is", "was", "were", "were");
        Test test189 = new Test("English Test 19", "Was it raining …………..you woke up this morning?", "while", "before", "when", "after", "when");
        Test test190 = new Test("English Test 19", "…………were you wearing when you went out this morning?", "when", "what", "where", "why", "what");
        Test test191 = new Test("English Test 20", "Have you ever heard the story …… the princess and the frog?", "in", "at", "on", "of", "of");
        Test test192 = new Test("English Test 20", "What was she…………..about?", "thought", "think", "thinking", "thinked", "thinking");
        Test test193 = new Test("English Test 20", "When he heard the noise he asked me what was………on", "happening", "being", "getting", "going", "going");
        Test test194 = new Test("English Test 20", "Your chocolate cake tastes……………", "deliciously", "delicious", "well", "safely", "delicious");
        Test test195 = new Test("English Test 20", "The report  tonight is coming………..by satellite from the Olympic Games", "Live", "lively", "Direct", "Immediately", "Live");
        Test test196 = new Test("English Test 20", "We arrived………..to have some coffee before class.", "enough early", "too early", "early enough", "early too", "early enough");
        Test test197 = new Test("English Test 20", "He always arrives for the ………….very early", "appoint", "appointed", "appointing", "Appointment", "Appointment");
        Test test198 = new Test("English Test 20", "He …………… to the website amazon.com every day.", "logs off ", "logs off", "logs on", "logs from ", "logs from");
        Test test199 = new Test("English Test 20", "Jeff Bezos borrowed $3,000,000 …………...his parents", "at", "from", "on", "with", "from");
        Test test200 = new Test("English Test 20", "I went …………...in the Himalayas two years ago.", "Trekking", "fishing", "walking", "jogging", "Trekking");
        database.insertTest(test1);
        database.insertTest(test2);
        database.insertTest(test3);
        database.insertTest(test4);
        database.insertTest(test5);
        database.insertTest(test6);
        database.insertTest(test7);
        database.insertTest(test8);
        database.insertTest(test9);
        database.insertTest(test10);
        database.insertTest(test11);
        database.insertTest(test12);
        database.insertTest(test13);
        database.insertTest(test14);
        database.insertTest(test15);
        database.insertTest(test16);
        database.insertTest(test17);
        database.insertTest(test18);
        database.insertTest(test19);
        database.insertTest(test20);
        database.insertTest(test21);
        database.insertTest(test22);
        database.insertTest(test23);
        database.insertTest(test24);
        database.insertTest(test25);
        database.insertTest(test26);
        database.insertTest(test27);
        database.insertTest(test28);
        database.insertTest(test29);
        database.insertTest(test30);
        database.insertTest(test31);
        database.insertTest(test32);
        database.insertTest(test33);
        database.insertTest(test34);
        database.insertTest(test35);
        database.insertTest(test36);
        database.insertTest(test37);
        database.insertTest(test38);
        database.insertTest(test39);
        database.insertTest(test40);
        database.insertTest(test41);
        database.insertTest(test42);
        database.insertTest(test43);
        database.insertTest(test44);
        database.insertTest(test45);
        database.insertTest(test46);
        database.insertTest(test47);
        database.insertTest(test48);
        database.insertTest(test49);
        database.insertTest(test50);
        database.insertTest(test51);
        database.insertTest(test52);
        database.insertTest(test53);
        database.insertTest(test54);
        database.insertTest(test55);
        database.insertTest(test56);
        database.insertTest(test57);
        database.insertTest(test58);
        database.insertTest(test59);
        database.insertTest(test60);
        database.insertTest(test61);
        database.insertTest(test62);
        database.insertTest(test63);
        database.insertTest(test64);
        database.insertTest(test65);
        database.insertTest(test66);
        database.insertTest(test67);
        database.insertTest(test68);
        database.insertTest(test69);
        database.insertTest(test70);
        database.insertTest(test71);
        database.insertTest(test72);
        database.insertTest(test73);
        database.insertTest(test74);
        database.insertTest(test75);
        database.insertTest(test76);
        database.insertTest(test77);
        database.insertTest(test78);
        database.insertTest(test79);
        database.insertTest(test80);
        database.insertTest(test81);
        database.insertTest(test82);
        database.insertTest(test83);
        database.insertTest(test84);
        database.insertTest(test85);
        database.insertTest(test86);
        database.insertTest(test87);
        database.insertTest(test88);
        database.insertTest(test89);
        database.insertTest(test90);
        database.insertTest(test91);
        database.insertTest(test92);
        database.insertTest(test93);
        database.insertTest(test94);
        database.insertTest(test95);
        database.insertTest(test96);
        database.insertTest(test97);
        database.insertTest(test98);
        database.insertTest(test99);
        database.insertTest(test100);
        database.insertTest(test101);
        database.insertTest(test102);
        database.insertTest(test103);
        database.insertTest(test104);
        database.insertTest(test105);
        database.insertTest(test106);
        database.insertTest(test107);
        database.insertTest(test108);
        database.insertTest(test109);
        database.insertTest(test110);
        database.insertTest(test111);
        database.insertTest(test112);
        database.insertTest(test113);
        database.insertTest(test114);
        database.insertTest(test115);
        database.insertTest(test116);
        database.insertTest(test117);
        database.insertTest(test118);
        database.insertTest(test119);
        database.insertTest(test120);
        database.insertTest(test121);
        database.insertTest(test122);
        database.insertTest(test123);
        database.insertTest(test124);
        database.insertTest(test125);
        database.insertTest(test126);
        database.insertTest(test127);
        database.insertTest(test128);
        database.insertTest(test129);
        database.insertTest(test130);
        database.insertTest(test131);
        database.insertTest(test132);
        database.insertTest(test133);
        database.insertTest(test134);
        database.insertTest(test135);
        database.insertTest(test136);
        database.insertTest(test137);
        database.insertTest(test138);
        database.insertTest(test139);
        database.insertTest(test140);
        database.insertTest(test141);
        database.insertTest(test142);
        database.insertTest(test143);
        database.insertTest(test144);
        database.insertTest(test145);
        database.insertTest(test146);
        database.insertTest(test147);
        database.insertTest(test148);
        database.insertTest(test149);
        database.insertTest(test150);
        database.insertTest(test151);
        database.insertTest(test152);
        database.insertTest(test153);
        database.insertTest(test154);
        database.insertTest(test155);
        database.insertTest(test156);
        database.insertTest(test157);
        database.insertTest(test158);
        database.insertTest(test159);
        database.insertTest(test160);
        database.insertTest(test161);
        database.insertTest(test162);
        database.insertTest(test163);
        database.insertTest(test164);
        database.insertTest(test165);
        database.insertTest(test166);
        database.insertTest(test167);
        database.insertTest(test168);
        database.insertTest(test169);
        database.insertTest(test170);
        database.insertTest(test171);
        database.insertTest(test172);
        database.insertTest(test173);
        database.insertTest(test174);
        database.insertTest(test175);
        database.insertTest(test176);
        database.insertTest(test177);
        database.insertTest(test178);
        database.insertTest(test179);
        database.insertTest(test180);
        database.insertTest(test181);
        database.insertTest(test182);
        database.insertTest(test183);
        database.insertTest(test184);
        database.insertTest(test185);
        database.insertTest(test186);
        database.insertTest(test187);
        database.insertTest(test188);
        database.insertTest(test189);
        database.insertTest(test190);
        database.insertTest(test191);
        database.insertTest(test192);
        database.insertTest(test193);
        database.insertTest(test194);
        database.insertTest(test195);
        database.insertTest(test196);
        database.insertTest(test197);
        database.insertTest(test198);
        database.insertTest(test199);
        database.insertTest(test200);
    }
    void addDbExtra(){
        Extra st1  = new Extra("A Baby and a Sock", "The mother gave her baby a red apple. The baby tried to eat the apple. His mouth was too small. And he didn't have any teeth. His brother took the apple. His brother ate the apple. The baby cried. His brother gave the baby a blue ball to play with. The baby smiled. His brother took the ball from the baby. He rolled the ball on the floor. The brown and white dog picked up the ball. The dog chewed on the ball. The baby cried again. His brother picked up the cat. He put the cat on the bed with the baby. The baby pulled the cat's tail. The cat jumped off the bed. The dog chased the cat. The baby cried again. His brother let the baby hold a sock. The baby played with the sock. The baby was happy.");
        Extra st2  = new Extra("Birds and a Baby", "The baby was lying on her back. A blue bird flew in through the window. The blue bird had blue eyes. It sat on the baby's crib. The bird had a bell around its neck. The bell rang. The baby smiled. The baby reached for the bell. The bird shook its head. The bell fell off the bird's neck. It fell next to the baby. The baby picked up the bell. The baby rang the bell. Another blue bird flew in through the window. This blue bird also had blue eyes. The baby had brown eyes. The birds looked at the baby. The baby looked at the birds. The baby rang the bell again. Both birds flew away. The baby started to cry. His mama came into the room. The baby smiled. Mama saw the bell. She asked the baby where the bell came from. The baby pointed at the window.");
        Extra st3  = new Extra("An Apple Pie", "The tree was full of red apples. The farmer was riding his brown horse. He stopped under the tree. He reached out and picked an apple off a branch. He bit into the raw apple. He enjoyed the apple. His horse turned its head to look at him. The farmer picked another apple off the tree. He gave it to the horse. The horse ate the raw apple. The horse enjoyed the apple. The farmer put a dozen apples into a bag. He rode the horse back home. He put the horse in the barn. He walked into his house. The cat rubbed up against his leg. He gave the cat a bowl of warm milk. He sat down on the sofa. He opened a book to read. His wife came home. She cooked the raw apples. She made an apple pie. They ate bread and hot soup for dinner. They enjoyed the bread and soup. They had hot apple pie for dessert. They both enjoyed the apple pie");
        Extra st4  = new Extra("Hugging is", "Hugging is healthy. It helps the immune system, cures depression, reduces stress and induces sleep. It’s invigorating, rejuvenating and has no unpleasant side effects. Hugging is nothing less than a miracle drug.Hugging is all natural. It is organic, naturally sweet, no artificial ingredients, non-polluting, environmentally friendly and 100 percent wholesome.Hugging is the ideal gift. Great for any occasion, fun to give and receive, shows you care, comes with its own wrapping and, of course, fully returnable.Hugging is practically perfect. No batteries to wear out, inflation-proof, non-fattening, no monthly payments, theft-proof and nontaxable.Hugging is an underutilized resource with magical powers. When we open our hearts and arms we encourage others to do the same.Think of the people in your life. Are there any words you’d like to say? Are there any hugs you want to share? Are you waiting and hoping someone else will ask first? Please don’t wait! Initiate! – Charles Faraone. We need four hugs a day for survival, eight hugs a day for maintenance, and twelve hugs a day for growth. -Virginia Satir");
        Extra st5  = new Extra("A broken pot", "A water bearer in India had two large pots, each hung on the ends of a pole which he carried across his neck. One of the pots had a crack in it, while the other pot was perfect and always delivered a full portion of water. At the end of the long walk from the stream to the house, the cracked pot arrived only half full. For a full two years this went on daily, with the bearer delivering only one and a half pots full of water to his house. Of course, the perfect pot was proud of its accomplishments, perfect for which it was made. But the poor cracked pot was ashamed of its own imperfection, and miserable that it was able to accomplish only half of what it had been made to do. After two years of what it perceived to be a bitter failure, it spoke to the water bearer one day by the stream. “I am ashamed of myself, and I want to apologize to you. I have been able to deliver only half my load because this crack in my side causes water to leak out all the way back to your house. Because of my flaws, you have to do a lot of this work, and you don’t get full value from your efforts,” the pot said. The bearer said to the pot, “Did you notice that there were flowers only on your side of the path, but not on the other pot’s side? That’s because I have always known about your flaw, and I planted flower seeds on your side of the path, and every day while we walk back, you’ve watered them. For two years I have been able to pick these beautiful flowers to decorate the table. Without you being just the way you are, there would not be this beauty to grace the house.”");
        Extra st6  = new Extra("Puppies for sale", "A store owner was tacking a sign above his door that read “Puppies for Sale”. Signs have a way of attracting children, and soon a little boy appeared at the store and asked, “How much are you gonna sell those puppies for?” The store owner replied, “Anywhere from $30 to $50.” The little boy reached into his pocket and pulled out some change. “I have $2.37, can I look at them?” The store owner smiled and whistled. Out of the back of the store came his dog running down the aisle followed by five little puppies. One puppy was lagging considerably behind. Immediately the little boy singled out the lagging, limping puppy.“What’s wrong with that little dog?” he asked. The man explained that when the puppy was born the vet said it had a bad hip socket and would limp for the rest of it’s life. The little boy got really excited and said “That’s the puppy I want to buy!” The man replied “No, you don’t want to buy that little dog. If you really want him, I’ll give him to you.” The little boy got upset. He looked straight into the man’s eyes and said, “I don’t want you to give him to me. He is worth every bit as much as the other dogs and I’ll pay the full price. In fact, I will give you $2.37 now and 50 cents every month until I have him paid for.” The man countered, “You really don’t want to buy this puppy, son. He’s never gonna be able to run, jump and play like other puppies.” The little boy reached down and rolled up his pant leg to reveal a badly twisted, crippled left leg supported by a big metal brace. He looked up at the man and said, “Well, I don’t run so well myself and the little puppy will need someone who understands.” The man was now biting his bottom lip. Tears welled up in his eyes… He smiled and said, “Son, I hope and pray that each and every one of these puppies will have an owner such as you.”");
        Extra st7  = new Extra("An act of kindness", "President Abraham Lincoln often visited hospitals to talk with wounded soldiers during the Civil War. Once, doctors pointed out a young soldier who was near death and Lincoln went over to his bedside. “Is there anything I can do for you now?” asked the president. The soldier obviously didn’t recognize Lincoln, and with some effort he was able to whisper, “Would you please write a letter to my mother?” A pen and paper were provided and the president carefully began to write down what the young man was able to say: “My dearest mother, I was badly hurt while doing my duty. I’m afraid I’m not going to recover. Don’t grieve too much for me, please. Kiss Mary and John for me. May God bless you and father.” The soldier was too weak to continue, so Lincoln signed the letter for him and added, “Written for your son by Abraham Lincoln.”  The young man asked to see the note and was astonished when he discovered who had written it. “Are you really the president?” he asked. “Yes, I am,” Lincoln replied quietly. Then he asked if there was anything else he could do. “Would you please hold my hand?” the soldier asked. “It will help to see me through to the end.” In the hushed room, the tall gaunt president took the soldier’s hand in his and spoke warm words of encouragement until death came. – The Best of Bits & Pieces");
        Extra st8  = new Extra("Heart song", "There was a great man who married the woman of his dreams. With their love, they created a little lovely girl. When the little girl was growing up, the great man would hug her and tell her, “I love you, little girl.” The little girl would pout and say, “I’m not a little girl anymore.” Then the man would laugh and say, “But to me, you’ll always be my little girl.” The little girl who-was-not-little-anymore decided to leave her home and went into the world. As she learned more about herself, she learned more about the man. One of his strengths was his ability to express his love to his family. It didn’t matter where she went in the world, the man would call her and say, “I love you, little girl.” The day came when the little girl who-was-not-little-anymore received anunexpected phone call. The great man was damaged. He had had a stroke. He couldn’t talk, smile, walk, hug, dance or tell the little girl who-was-not-little-anymore that he loved her. And so she went to the side of the great man. When she walked into the room and saw him, he looked small and not strong at all. He looked at her and tried to speak, but he could not. The little girl did the only thing she could do. She sat next to the great man, and drew her arms around the useless shoulders of her father. Her head on his chest, she thought of many things. She remembered she had always felt protected and cherished by the great man. She felt grief for the loss she was to endure, the words of love that had comforted her. And then she heard from within the man, the beat of his heart. The heart beat on, steadily unconcerned about the damage to the rest of the body. And while she rested there, the magic happened. She heard what she needed to hear. His heart beat out the words that his mouth could no longer say… I love you, little girl… I love you, little girl… and she was comforted.");
        Extra st9  = new Extra("Don’t Be Late", "He was late. He was always late. Why did time always go so fast? Time always went too fast. He looked at his watch. He looked at the clock on the wall. They both said 6:10. He had to leave in 10 minutes. But first he had to shave. Then he had to brush his teeth. Then he had to get dressed. Shaving took time. Brushing his teeth took time. Getting dressed took time. But he had only 10 minutes. So he turned off the TV. He turned off the radio, too. He turned off the table lamp. He went into the bathroom. He shaved. He brushed his teeth. He went into his bedroom. He got dressed. He looked at his watch. He looked at the clock on the wall. They both said 6:25. He had to hurry. He went out to his car. He drove fast. He slowed down at a stop sign. A cop saw him. The cop wrote him a ticket. Why didn't you stop at the stop sign? the cop asked. But officer, I was in a hurry, he said. The cop gave him the ticket. The cop said, Leave home earlier next time");
        Extra st10 = new Extra("A Good Meal", "The children were hungry. They looked out the window. Where was their mother? She walked into the house. The children ran over to her. Mama, we're so hungry, they both said. She said lunch was coming. She walked into the kitchen. She opened a can of chicken soup. She poured the soup into a pot. She added water. She put the pot on the stove. She made two peanut butter and jelly sandwiches. She sliced an apple. The soup was hot. She poured it into two bowls. She put the sandwiches on two plates. She put apple slices on each plate. She put the bowls and plates on the table. The children ran to the table. Thank you, mommy! they said. Then they started eating. The cat and the dog watched them eat");
        Extra st11 = new Extra("Life Is Good", "I am happy. I have many friends. I have a large family. I have four brothers and four sisters. I am in the middle. Four brothers are older than me. Four sisters are younger than me. I go to school. I am in the sixth grade. I like my teachers. My teachers like me. I have friends in every class. My favorite class is hiExtra. I like to read about hiExtra. HiExtra is a Extra about our past. Soon we will all be hiExtra. Then kids in school will read about us. I hope they like our stories. My best friend is Bobby. Bobby and I do many things together. We swim together. We play basketball together. We ride our bikes together. I have many other friends. We all go to the mall on weekends. We go to movies. We go to restaurants. We tell jokes. We laugh. We have fun. Life is great.");
        Extra st12 = new Extra("Corn for People and Animals", "The farmer drives a tractor. The tractor digs up the ground. He plants yellow corn in the ground.  He plants the yellow corn in the spring. The corn grows in the summer. The rain helps the corn grow. If there is no rain, the corn dies. If there is a lot of rain, there is a lot of corn. He harvests the yellow corn in late summer. He sells the corn at his vegetable stand. He sells one ear for 25 cents. He sells four ears for $1. He sells all his corn in just one month. The neighbors love his corn. The corn is fresh. It is bright yellow. It is tasty. It is delicious. The birds love his corn, too. They don't pay for it. They eat it while it is in the field. They don't cook it. They eat it raw. The farmer doesn't get angry. Birds have to eat, too. So do cows. The farmer has one cow. He gives his cow fresh corn every summer. The cow loves the corn. It eats a lot of yellow corn in the summer. Sometimes it makes yellow milk. ");
        Extra st13 = new Extra("Daddy Likes Beer", "The little girl was thirsty. She wanted something to drink. She opened the refrigerator. She looked inside. She saw milk. She saw soda. She saw orange juice. She saw beer. She wondered what beer tasted like. Her daddy drank beer every day. Beer must be good. If Daddy likes it, it must taste good. She grabbed a can of beer. She opened the beer. She smelled it. She couldn't smell anything. She swallowed some. Yuck! she said. The beer was horrible. How could Daddy drink that stuff? She put the can back into the refrigerator. Daddy could finish it when he got home. She grabbed the milk. She poured some into a glass. She added chocolate syrup to the milk. She stirred the milk. Now she had chocolate milk. She loved chocolate milk. Poor Daddy, she thought. He likes beer more than chocolate milk.   ");
        Extra st14 = new Extra("She Writes Letters", "She will write a letter to her grandma. She will write about her day at school. She will write about her classmates. She will write about her teacher. She will write about the classroom. She will write about her school bus. She will write about her school bus driver. She won't write about her pets. She won't write about her fat black cat. She won't write about her little red dog. She won't write about her soft white rabbit. She won't write about her big brown horse. That's because she doesn't have a big brown horse. Not yet. She wants a big brown horse for her birthday. She will write a letter to her daddy about the horse. She will ask her daddy for a big brown horse. A big brown horse will be a perfect birthday gift. She will never want another birthday gift. A horse will make her happy forever. The letter to her daddy will ask for a horse. Maybe daddy will give her a horse. Then she will write a new letter to her grandma. She will tell grandma about the new brown horse.  ");
        Extra st15 = new Extra("Squares and Circles", "Different shapes and forms are everywhere. Boxes and street signs are square or rectangular. Balls and wheels are round. The sun and moon are round. Wedding rings are round. Eggs and light bulbs are almost round. Pyramids and arrow tips are triangular. Tables and books are square or rectangular. Doors and refrigerators are rectangular. A stop sign has eight sides. A triangle has three sides. Pencils and pens are long and round. Your toes are short and round. Many things have various shapes. Humans and animals have various shapes. Faces have various shapes. Clouds have various shapes. Houses and buildings have various shapes. Airplanes have various shapes. Other things have weird shapes. Bicycles and tricycles have weird shapes. Countries have weird shapes. Tools and machines have weird shapes. Shapes can be beautiful, too. Boys think that a skateboard or a soccer ball has a beautiful shape. Men think that women have the most beautiful shape of all.  ");
        Extra st16 = new Extra("Homeless People", " Los Angeles is a big city. There are millions of people here. But thousands of people have no home. They are homeless people. They live on the sidewalks. They sleep on the sidewalks. They are called street people. They don't have cars. They have shopping carts. They fill the carts with their belongings. They put their extra clothes into the carts. They put their blankets into the carts. Many homeless people live downtown. They live near the newspaper building. They live near the courthouse. They live near fancy condos. They have no money. They sit on the sidewalk all day. People walk by them. They ask people for money. People say they don't have any money. There are missions downtown. These missions feed homeless people. They give them free lunches. They feed them every day. Some missions have beds. Homeless people sleep in these beds. But there are more homeless people than beds. There are not enough beds for the homeless people. So most homeless people sleep on the sidewalk. They sleep next to their shopping carts. ");
        Extra st17 = new Extra("Go to the Park", "Chuck wanted to go to the park after dinner. His mom wanted him to stay home after dinner. She didn't want him to go to the park. She said it was dark at the park. But Chuck said it wasn't dark at the park. There are lights at the park, Mom, he said. But she said there were only a few lights at the park. She said there were many dark places in the park. Bad people go to the park at night, she said. Bad people do bad things. They do bad things to good people. You are a good person. I don't want something bad to happen to you. Chuck said, Nothing bad will happen to me. I will go with my two friends. We will be together. All three of us will be together. We will stay away from the dark places. We will stay under the lights.");
        Extra st18 = new Extra("A Birthday Dress", "It was Ellen's 12th birthday. Ellen was 12 years old. Her mom took her shopping. They went shopping at the mall. You can pick out a dress. You can pick out a pretty dress, Mom said. I will pick out a pretty, blue dress, Ellen said. They went into JC Penney. JC Penney sells lots of dresses. Ellen saw a blue dress that she liked. I like that dress, Mom, she said. She took the dress into the dressing room. She put on the dress. It fit her well. She walked out of the dressing room. The dress fits you well, said Mom. Can I have it? Ellen asked. Of course you can have it, dear. It's your birthday present, said Mom. But it's not on sale, said Ellen. We always buy everything on sale. It's your birthday, dear. On your birthday, we can pay full price, said Mom.");
        Extra st19 = new Extra("A Small Apartment", "The big family lived in a one-bedroom apartment. Their apartment had only one bedroom. Mom and Dad slept in the bedroom. The two babies also slept in the bedroom. Four people slept in the bedroom. Four children slept in the living room. Two sisters slept in the living room. Two brothers slept in the living room. All four of them slept in the living room. They slept on air mattresses. They leaned the air mattresses against the wall in the daytime. They put the air mattresses on the floor in the nighttime. They all liked to sleep on the air mattresses. But the girls didn't like to sleep next to the boys. Daddy, we don't like to sleep next to the boys. We want our own bedroom. When will we get our own bedroom? asked one girl. You'll get your own bedroom when I get a better job, Daddy said.");
        Extra st20 = new Extra("Where’s Kitty?", "Kathy said, Here, Kitty, Kitty! But Kitty didn't come. Where was Kitty? Kitty always came home for dinner. Kathy said it again. Here, Kitty, Kitty! But Kitty didn't come. Kathy stayed up late. She waited for Kitty to come in. Kitty always came in through the pet door. Kathy finally fell asleep. She woke up the next morning. Here, Kitty, Kitty! she said. But Kitty was not home. Where could Kitty be, Kathy thought. Where could Kitty be? Kathy called the police. A policeman answered the phone. My cat didn't come home last night, Kathy said. I'm sorry to hear that, said the policeman. What is your cat's name? Kathy said her cat's name was Kitty. That's a nice name, said the policeman. What color is Kitty? Kathy said that Kitty was black. Okay, don't worry, said the policeman. We'll find Kitty. Someone probably ran over her.");
        Extra st21 = new Extra("Make Some Coffee", "She took the bag of coffee beans out of the freezer. She kept them in the freezer because the instructions on the bag said that is the best place. She poured the beans into the grinder. She pressed the grinder button for 10 seconds. Now she had ground coffee. She put a paper filter into a plastic cone. She put the cone on top of a coffee cup. She poured the ground coffee into the cone. Then she poured hot water into the cone. The hot water dripped through the ground coffee. She waited until the cup was full of hot coffee. She threw away the filter and the ground coffee. She took her cup of coffee to the dining room table. She sipped her coffee while she read the newspaper.  ");
        Extra st22 = new Extra("Time to Shop", "It was time to go to the market. He had no bananas, no apples, and no milk. He got into his car and drove to the market. It was only five minutes away. The parking lot was almost empty. Good, he thought. He wouldn't have to stand in a long line. He parked his car and walked over to the shopping cart area. He pulled out one of the carts and pushed it ahead of him into the store. Inside, he grabbed an alcohol wipe and wiped the handle of the cart. Then he grabbed another wipe and wiped his own hands. You can never be too careful, he thought. He turned left and walked over to the produce section. Today was his lucky day. Apples were on sale, a dollar a pound. Usually they were two dollars a pound or more. He put 10 apples into a plastic bag and weighed the bag. It was three pounds. He walked over to the bananas. They were the regular price, 79 cents a pound. He bought three pounds of bananas. When he saw the carrots, he remembered that he needed carrots, too. He put a two-pound bag of carrots into his cart. They were only $1.29. He walked to the dairy section and saw that a gallon of milk was $4. He put one into his cart and walked back to the front of the store. He paid for his food, got his receipt, and walked out to his car. He put the food into his trunk and drove home.        ");
        Extra st23 = new Extra("The Painter", "The painter was on the ladder. The ladder was on the sidewalk. The ladder was leaning against the wall. The painter was standing about 10 feet above the sidewalk. He was holding a spray gun. He was painting the wall with a spray gun. He was painting the wall white. The wall was part of the 99 Cents store. The store had big glass windows. The painter had taped plastic over the windows. Plastic covered the big glass windows. The painter wore goggles over his eyes. The goggles covered his eyes. Customers walked into the store. Customers walked out of the store. They walked under the ladder. They walked under the painter. Tiny drops of paint fell on the customers. Tiny drops of paint fell on the cars. Tiny drops of paint fell on the sidewalk. The painter didn't care. Tiny drops of paint were not his problem.   ");
        Extra st24 = new Extra("Catch Some Fish", "Let's go fishing, said the father. That's a good idea, said the mother. They put the kids into the car. They put the fishing rods into the car. They put the jar of worms into the car. They drove to the lake. The lake was huge. The name of the lake was Yellow Lake. It had yellow sand all around it. The sand looked like gold. But it wasn't gold. It was only sand. They parked the car. They got out of the car. They sat down on the sand. They put the worms on the hooks. They put the hooks into the water. They waited for the fish to bite the bait. They waited 30 minutes. Then one of the kids caught a fish. It was a trout. It was a rainbow trout. It had many colors, like a rainbow. But its belly was white. They took the trout off the hook. They put the trout into a bucket of water. The trout swam around in tiny circles. It was confused. Where did the big lake go? They caught three more trout. Then they went home. They had delicious fried fish for dinner. Can we go fishing every day? the kids asked their parents.");
        Extra st25 = new Extra("The Birthday Cake", "It was Jenny's fourth birthday. She was four years old. Her mom baked a cake for her. Her mom baked a chocolate cake for her. The cake had two layers. Her mom put vanilla frosting on the bottom layer. Her mom put vanilla frosting on the top layer. Her mom put vanilla frosting all around the cake. Now the chocolate cake was completely white. Her mom put four pink candles on top of the cake. Her dad lit the four pink candles. The four pink candles were lit. Jenny's mom and dad sat down next to Jenny. They sang Happy Birthday to her. Happy birthday to you, they sang. Jenny sang with her mom and dad. Happy birthday to me, she sang. Her mom said, Now make a wish and blow out the candles. Jenny made a wish. Then she blew out all four pink candles.");
        Extra st26 = new Extra("Life Will Be Better", "He was poor. He needed more money. He needed a good job. He had a job. But it wasn't a good job. It was a bad job. He was a waiter. He worked in a restaurant. It was a cheap restaurant. The meals were cheap. The customers were cheap. They usually gave him quarters for tips. Sometimes they gave him a dollar. Sometimes they gave him nothing. That made him angry. Why did they give him nothing? He was polite. He was helpful. Yet they gave him nothing. He wanted to kick those customers. But then he would go to jail. He didn't want to go to jail. So he went to school. School was free. He wanted to be a mechanic. He liked to fix things. He wanted to fix cars. He wanted to own a car shop. He would make money. He would hire other mechanics. They would work for him. He would buy a house. He would get married. He would have a family. Life would be good. Right now life was bad. But he would make it better.  ");
        database.insertExtra(st1); database.insertExtra(st2); database.insertExtra(st3); database.insertExtra(st4);
        database.insertExtra(st5); database.insertExtra(st6); database.insertExtra(st7); database.insertExtra(st8);
        database.insertExtra(st9); database.insertExtra(st10); database.insertExtra(st11); database.insertExtra(st12);
        database.insertExtra(st13); database.insertExtra(st14); database.insertExtra(st15); database.insertExtra(st16);
        database.insertExtra(st17); database.insertExtra(st18); database.insertExtra(st19); database.insertExtra(st20);
        database.insertExtra(st21); database.insertExtra(st22); database.insertExtra(st23); database.insertExtra(st24);
        database.insertExtra(st25); database.insertExtra(st26);
    }
}
